---
- hosts: web
  vars:
   db_password: password
   server_name: curriculum
   service_name: curriculum
   service_version: 1.0
   app_key: QujjaJs3fxwtnTl7FiqhEEn1ACkf7YZW
   app_env: test
   db_host: localhost
   db_database: curriculum
   db_username: curriculum
   db_port: 3306
   service_dir: /usr/share/nginx/{{ service_name }}
  tasks:
    - name: replaces the line and sets SELINUX to be permissive right away 
      become: yes
      lineinfile: dest=/etc/sysconfig/selinux regexp="^SELINUX=" line="SELINUX=permissive"

    - become: yes
      command: setenforce 0
      
    - name: Installs (EPEL) Extended Packages for Enterprise Linux
      become: yes
      yum: name=epel-release update_cache=yes state=present

    - name: Installs nginx
      become: yes
      yum: name=nginx,php,php-fpm,php-ldap,php-mbstring,php-mcrypt,php-mysql,php-phpunit-PHPUnit update_cache=yes state=present
      register: nginx_install

    - name: Downloads composer into directory
      become: yes
      shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

    - name: Copy module that copies from the nginx source to /etc 
      become: yes
      copy: src=web/nginx.conf dest=/etc/nginx/nginx.conf mode=0640
      register: nginx_conf

#nothing wrong
    - name: template that injects service_name
      become: yes
      template: src=web/vhost.conf.j2 dest=/etc/nginx/conf.d/{{ service_name }}.conf mode=0644
      register: vhost_conf

#problem
    - name: Templates  
      become: yes
      template: src=web/php.ini.j2 dest=/etc/php.ini mode=0644
      register: php_conf
#fine
    - name:Copy module from source to destination 
      become: yes
      copy: src=web/php-fpm-web.conf dest=/etc/php-fpm.d/www.conf mode=0644
      register: php_fpm_conf

#changes systemd to service 
    - name: Boots nginx on restart
      become: yes
      service: name=nginx state=restarted enabled=yes
      when: nginx_install|changed or nginx_conf|changed or vhost_conf|changed

    - name: Boots php-fpm on restart
      become: yes
      service: name=php-fpm state=restarted enabled=yes
      when: nginx_install|changed or php_conf|changed or php_fpm_conf|changed

    - name: Sets attributes of files
      become: yes
      file: path="{{ service_dir }}" state=directory

    - name: unzips an archive after copying from local machine
      become: yes
      unarchive: src=web/{{ service_name }}.tgz dest="{{ service_dir }}" mode=0755

    - name: Installs composer 
      become: yes
      command: /usr/local/bin/composer update chdir={{ service_dir }}

    - name: Changes permissions 
      become: yes
      command: chmod -R 0777 storage chdir="{{ service_dir }}"

    - name: Changes permissions
      become: yes
      command: chown -R nginx:nginx . chdir="{{ service_dir }}"

    - name: Template that injects service_dir 
      become: yes
      template: src=web/env.j2 dest="{{ service_dir }}/.env" mode=0644 owner=nginx
