---
- hosts: web
  vars:
    server_name: curriculum
    service_name: curriculum
    service_version: 1.0
    app_env: test
    db_host: tf-20161214235901012718526smb.ceym2bf0akjd.us-west-2.rds.amazonaws.com
    db_database: curriculum
    db_username: curriculum
    db_port: 3306
    service_dir: /usr/share/nginx/{{ service_name }}
  tasks:
    - name: Include Secret 
      include_vars: secret.yml

    - name: Install epel-release
      become: yes
      yum: name=epel-release update_cache=yes state=present

    - name: Install PHP 5.4
      become: yes
      shell: yes | yum install php54 php54-fpm php54-ldap php54-mbstring php54-mcrypt php54-pdo

    - name: Install nginx
      become: yes
      yum: name=nginx update_cache=yes state=present
      register: nginx_install
    
    - name: Download installer
      become: yes
      get_url: 
        url: https://getcomposer.org/installer
        dest: /usr/local/bin/composer
        mode: 0777
        
    - name: Composer
      become: yes
      shell: php /usr/local/bin/composer --install-dir=/usr/local/bin --filename=composer

    - name: configure nginx
      become: yes
      copy: src=~/cit-360/ansible/web/nginx.conf dest=/etc/nginx/nginx.conf mode=0000
      register: nginx_conf

    - name: Configure vhost_conf
      become: yes
      template: src=~/cit-360/ansible/web/vhost.conf.j2 dest=/etc/nginx/conf.d/{{ service_name }}.conf mode=0644
      register: vhost_conf

    - name: register php conf
      become: yes
      template: src=~/cit-360/ansible/web/php.ini.j2 dest=/etc/php.ini mode=0644
      register: php_conf

    - name: register php_fpm_conf
      become: yes
      copy: src=~/cit-360/ansible/web/php-fpm-web.conf dest=/etc/php-fpm.d/www.conf mode=0644
      register: php_fpm_conf

    - name: restart nginx
      become: yes
      service: name=nginx state=restarted enabled=yes
      when: nginx_install|changed or nginx_conf|changed or vhost_conf|changed

    - name: restart php-fpm
      become: yes
      service: name=php-fpm state=restarted enabled=yes
      when: nginx_install|changed or php_conf|changed or php_fpm_conf|changed

    - name: directory path file
      become: yes
      file: path="{{ service_dir }}" state=directory

    - name: unzip  
      become: yes
      unarchive: src=~/cit-360/ansible/web/{{ service_name }}.tgz dest="{{ service_dir }}" mode=0755

    - name: updates composer
      become: yes
      command: /usr/local/bin/composer update chdir={{ service_dir }}
      ignore_errors: True     

    - name: Gives read, write, execute permission
      become: yes
      file: recurse=yes path={{ service_dir }}/storage mode=0777

    - name: Permission for nginx
      become: yes
      file: recurse=yes path={{ service_dir }} owner=nginx group=nginx

    - name: web template
      become: yes
      template: src=~/cit-360/ansible/web/env.j2 dest="{{ service_dir }}/.env" mode=0644 owner=nginx
