---
- hosts: db
  vars:
    db_password: password
  tasks:
<<<<<<< HEAD
=======

    - name: Include the secret file that contains db password 
      include_vars: secrets.yml  

>>>>>>> 6e8be0e3d0585c546077ef41277dfc31ff4d3164
    - name:  Copy module that copies the local host on to remote host
      become: yes
      copy: src=~/cit-360/ansible/db/MariaDB.repo dest=/etc/yum.repos.d/MariaDB.repo mode=0644
    
    - name: install MariaDB  
      become: yes
<<<<<<< HEAD
      package: name=MariaDB-client update_cache=yes state=present
=======
      yum: name=MariaDB-server,MariaDB-client update_cache=yes state=present
>>>>>>> 6e8be0e3d0585c546077ef41277dfc31ff4d3164

    - name: Unzips package from remote to host machine 
      become: yes
      unarchive: src=db/db.tgz dest=~/ mode=0777

    - name: Run database comand, inject the db_password on to localhost
<<<<<<< HEAD
      command: ./make_databases.sh {{ db_password }} tf-20161213222823545614863pko.ceym2bf0akjd.us-west-2.rds.amazonaws.com chdir=~/db
      ignore_errors: True 
      
      
=======
      command: ./make_databases.sh {{ db_password }} f-20161213222823545614863pko.ceym2bf0akjd.us-west-2.rds.amazonaws.com:3306 chdir=~/db
      ignore_errors: True
      
      
>>>>>>> 6e8be0e3d0585c546077ef41277dfc31ff4d3164
