---
- hosts: db
  tasks:
    - name:  Copy module that copies the local host on to remote host
      become: yes
      copy: src=~/cit-360/ansible/db/MariaDB.repo dest=/etc/yum.repos.d/MariaDB.repo mode=0644

    - name: Install MariaDB client
      become: yes
      package: name=MariaDB-client update_cache=yes state=present

    - name: Unzips package from remote to host machine 
      become: yes
      unarchive: src=db/db.tgz dest=~/ mode=0777
    
    - name: Run database command, inject the db_password on to localhost
      command: ./make_databases.sh {{ db_password }} tf-20161214201646319495338aim.ceym2bf0akjd.us-west-2.rds.amazonaws.com chdir=~/db
      ignore_errors: True 
